### ISSUE TITLE
Allow links in native obsidian format

### ISSUE THREAD

**Issue by JJger148** [joethei/obsidian-plantuml#5]
automatically generate links that can be clicked, when I include a link.

**Comment by joethei** [comment]
Do you mean web links, or links inside your vault ?

If you mean web links: those are already possible, just use `plantuml-map` as the language
instead of `plantuml`.
For internal links they are possible if they are specified as [outlined here.](https://help.obsidian.md/Advanced+topics/Using+obsidian+URI).
Support for internal links in the native obsidian format is on my to-do list.
